### ISSUE TITLE
Introduce Events for all base objects as Clingon

### ISSUE THREAD

**Issue by nikolagsiderov** [nikolagsiderov/APPartment#190]
*Events, clingons.. what are these things?
Clingons are the metainfo objects we have for all objects inheriting BaseObject.cs class.
Clingons are **Comments** and **Images** at the moment.*

We want to add a new clingon, named **Events**. Right after **Images** in the tabbing.
What benefits do **Events** give us? Here are some examples of use cases:
1. Lets say you create an object in *Issues* module. You have an *issue*, named 'No internet access'. You have an issue, which is that you do not have internet. You call the internet provider, they tell you they will come next Wednesday. With **Events** you can now add this as an event in this *issue*. You add, lets say, an *event* named: Internet provider coming and description: They said.... So when you add this event in this issue object, it will be now viewable in this issue, but more importantly we want it viewable in the **General Calendar**.

How the **General Calendar** will get this event is not your concern, this will be another task on its own. You just have to provide the ability for users to create **Events** as a clingon in base objects.

**Tech part**
1. Create `Event.cs` in `APPartment.Data.csproj` in Server/Models/MetaObjects
2. Set attribute '[Table("Event", Schema= "dbo")]', make `Event.cs` inherit 'IdentityBaseObject'
3. Give properties to `Event.cs`: `public DateTime StartDate`, `public DateTime EndDate`, `public long TargetObjectId`
4. Set all properties in model with the `[FieldMappingForMainTable]` attribute
5. Provide and execute a SQL script to create [dbo].[Event] table with columns [Id] +  of the above mentioned properties + [ObjectId]
6. In `APPartment.Data.csproj` in Server/Models/Base go to `BaseObject.cs` and add a new property below Images list: `public List<Event> Events`
7. In `APPartment.ORM.Framework.csproj` in Enums go to `ObjectTypes.cs` and add new enum value: `Event = 17`
8. Provide and execute a SQL script for inserting this new 'Event' object type in the DB (check out `APPartment.Data.csproj`/SQL/19. Populate ObjectType table.sql for more info, DO NOT modify this script, just add a new one for Event insertion, only one insert should be present in the script you execute and provide).
9. In `APPartment.UI.csproj` in Controllers/Base in `BaseCRUDController.cs` go to `region Clingons`, there you can see there are is for example a region for Comment. Create your own region for Events after the Images region and there you should implement 3 actions: `private List<Event> GetEvents(long targetObjectId) {}`, `public IActionResult GetAddEventView(Event event) {}`, `public IActionResult PostEvent(Event event) {}`
10. Create `_Events.cshtml` partial view in `APPartment.csproj` in Views/Shared (check out `_Images.cshtml` and structure it similarly with the same `@model APPartment.Data.Server.Models.Base.IdentityBaseObject`), inside there should a foreach (var event in Model.Events) {...} which will display all the existing events for the target object. If not there should be an `else` statement for 'No events have been added for this object.'
11. There should also be a button for 'Add' with actions or js functions which direct to the next to be implemented partial view.
12. The next partial view to be implement will be in the same place where we implement the `_Events.cshtml`, the partial view should be named 'GetAddEventView.cshtml' and inside this partial view, you should implement all the edit fields for the 'Event.cs' object. All fields will be: Name string field, Details string field, StartDate date field, EndDate date field, Participants multiselect field.
13. Participants? Here we will create the 'EventParticipant.cs' in `APPartment.Data.csproj` in Server/Models/MetaObjects
14. Set attribute '[Table("EventParticipant", Schema= "dbo")]', make `EventParticipant.cs` inherit 'IdentityBaseObject'
15. Give properties to `EventParticipant.cs`: `public long EventId`, `public long UserId`
16. Set all properties in model with the `[FieldMappingForMainTable]` attribute
17. Provide and execute a SQL script to create [dbo].[EventParticipant] table with columns [Id] +  of the above mentioned properties + [ObjectId]
18. In 'Event.cs' class object which we created 1. above, go there and add another property: `public List<EventParticipant> Participants` and DO NOT give it any attributes
19. In `APPartment.ORM.Framework.csproj` in Enums go to `ObjectTypes.cs` and add new enum value: `EventParticipant = 18`
20. Provide and execute a SQL script for inserting this new 'EventParticipant' object type in the DB (check out `APPartment.Data.csproj`/SQL/19. Populate ObjectType table.sql for more info, DO NOT modify this script, just add a new one for EventParticipant insertion, only one insert should be present in the script you execute and provide).
21. In the `GetEvents()`, `GetAddEventView()` and `PostEvent()` functions in `BaseCRUDController.cs` you added in 9. above add new logic for EventParticipants to be correctly handled and added to event objects

---

I expect lots of questions from you here... Do not worry, think, read the description here, try, if you get stuck, think, read the description again, if you get stuck again, another time and then if this flow continues, then you can ping me for more info! :)

Interesting task, involving all layers (ui, db, etc.)!

**Comment by Aleksandar210** [comment]
[Table("Event", Schema = "dbo")] what is the purpose of this attribute, now that we are using DbFirst how does it work with the attributes (I mean the DB)

**Comment by nikolagsiderov** [comment]
The APPORM framework needs these attributes in order to know which models with what tables work. If you want to learn more: right click on the attribute -> find all references and check out where it is being called and how the framework uses it.

**Comment by nikolagsiderov** [comment]
Actually, on second thoughts, the APPORM currently does not know about this attribute, but it will in near future, so we still need to use it.

**Comment by nikolagsiderov** [comment]
Opened issue #274 in next iteration.

**Comment by nikolagsiderov** [comment]
Added George to the project. We tested out if he has 'Write' rights, that's why we moved this issue. FYI.

**Comment by nikolagsiderov** [comment]
Lots of the requirements have changed here, since I originally wrote the description. We will make a call tonight and scope it out...
